# Generated by Django 5.0.2 on 2024-02-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetest',
            name='name',
            field=models.IntegerField(),
        ),
    ]
