# Generated by Django 5.0.2 on 2024-02-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_basetest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetest',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basetest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
